[package]
name = "pyroscope"
description = """
Pyroscope Profiler
"""
keywords = ["pyroscope", "profiler"]
authors = ["Abid Omar <contact@omarabid.com>"]
version = "0.4.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://pyroscope.io"
documentation  = "https://docs.rs/pyroscope"
repository = "https://github.com/pyroscope-io/pyroscope-rs"
readme = "README.md"
autobins = false
autoexamples = true 
autotests = true 
autobenches = true 

[workspace]
members = [
]
exclude = [
    "pyroscope_backends",
    "pyroscope_cli",
]

[[example]]
name = "internal-backend-void"
path = "examples/internal/backend-void.rs"

[[example]]
name = "internal-backend-void-run"
path = "examples/internal/backend-void-run.rs"

[[example]]
name = "internal-backend-pprof"
path = "examples/internal/backend-pprof.rs"

[[example]]
name = "internal-timer"
path = "examples/internal/timer.rs"

[[example]]
name = "internal-pyspy-connect"
path = "examples/internal/pyspy-connect.rs"

[[example]]
name = "internal-rbspy-connect"
path = "examples/internal/rbspy-connect.rs"

[dependencies]
thiserror ="1.0"
log = "0.4"
reqwest = { version = "0.11", features = ["blocking"]}
libc = "^0.2.66"

[dev-dependencies]
tokio = { version = "1.13", features = ["full"] }
pretty_env_logger = "0.4.0"
assert_matches = "1"
pyroscope_pprofrs = { path = "pyroscope_backends/pyroscope_pprofrs" }
pyroscope_rbspy = { path = "pyroscope_backends/pyroscope_rbspy" }
pyroscope_pyspy = { path = "pyroscope_backends/pyroscope_pyspy" }

[profile.dev]
opt-level=0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 4

[profile.release]
opt-level=3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.test]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 4

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
