name: Build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        package: [lib, cli, pprofrs, pyspy, rbspy]
    steps:
      - name: install libunwind (for pprof)
        continue-on-error: true
        run: sudo apt install libunwind8-dev

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: omarabid-forks/rs-toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo build for pyroscope library 
        uses: omarabid-forks/rs-cargo@v1
        if: matrix.package == 'lib'
        with:
          command: build

      - name: Cargo build for pyrosocpe-cli 
        uses: omarabid-forks/rs-cargo@v1
        if: matrix.package == 'cli'
        with:
          cwd: ./pyroscope_cli
          command: build

      - name: Cargo build for pprof-rs
        uses: omarabid-forks/rs-cargo@v1
        if: matrix.package == 'pprofrs'
        with:
          cwd: ./pyroscope_backends/pyroscope_pprofrs
          command: build

      - name: Cargo build for pyspy 
        uses: omarabid-forks/rs-cargo@v1
        if: matrix.package == 'pyspy'
        with:
          cwd: ./pyroscope_backends/pyroscope_pyspy
          command: build

      - name: Cargo build for rbspy 
        uses: omarabid-forks/rs-cargo@v1
        if: matrix.package == 'rbspy'
        with:
          cwd: ./pyroscope_backends/pyroscope_rbspy
          command: build
